-- Create tables for the assignment
CREATE TABLE departments (
  dept_id   NUMBER PRIMARY KEY,
  name      VARCHAR2(100) NOT NULL
);

CREATE TABLE employees (
  emp_id      NUMBER PRIMARY KEY,
  first_name  VARCHAR2(50),
  last_name   VARCHAR2(50),
  dept_id     NUMBER REFERENCES departments(dept_id),
  salary      NUMBER(12,2),
  on_leave    CHAR(1) DEFAULT 'N' CHECK (on_leave IN ('Y','N'))
);

CREATE TABLE bonuses (
  bonus_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  emp_id      NUMBER,
  dept_id     NUMBER,
  bonus_amt   NUMBER(12,2),
  created_at  DATE DEFAULT SYSDATE
);

-- optional: grant or constraints omitted for simplicity

